// Mocks generated by Mockito 5.4.4 from annotations
// in ballistics_wallet_flutter/test/bonus_tables_v2_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:ballistics_wallet_flutter/models/bonus_info.dart' as _i10;
import 'package:ballistics_wallet_flutter/models/ratio_and_bonus_info.dart'
    as _i5;
import 'package:ballistics_wallet_flutter/providers/wallet_providers.dart'
    as _i11;
import 'package:ballistics_wallet_flutter/repository/bonus_info_repository.dart'
    as _i8;
import 'package:ballistics_wallet_flutter/repository/users_repository.dart'
    as _i6;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i12;
import 'package:hive/hive.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:riverpod/src/internals.dart' as _i2;
import 'package:state_notifier/state_notifier.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProviderContainer_0 extends _i1.SmartFake
    implements _i2.ProviderContainer {
  _FakeProviderContainer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProviderSubscription_1<State1> extends _i1.SmartFake
    implements _i2.ProviderSubscription<State1> {
  _FakeProviderSubscription_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_2<E> extends _i1.SmartFake implements _i3.Box<E> {
  _FakeBox_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlwaysAliveRefreshable_3<T> extends _i1.SmartFake
    implements _i2.AlwaysAliveRefreshable<T> {
  _FakeAlwaysAliveRefreshable_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStateNotifierProviderElement_4<
        NotifierT extends _i4.StateNotifier<T>, T> extends _i1.SmartFake
    implements _i2.StateNotifierProviderElement<NotifierT, T> {
  _FakeStateNotifierProviderElement_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOverride_5 extends _i1.SmartFake implements _i2.Override {
  _FakeOverride_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBonusInfoAndRatio_6 extends _i1.SmartFake
    implements _i5.BonusInfoAndRatio {
  _FakeBonusInfoAndRatio_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlwaysAliveProviderListenable_7<State> extends _i1.SmartFake
    implements _i2.AlwaysAliveProviderListenable<State> {
  _FakeAlwaysAliveProviderListenable_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserState_8 extends _i1.SmartFake implements _i6.UserState {
  _FakeUserState_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStateProviderElement_9<T> extends _i1.SmartFake
    implements _i2.StateProviderElement<T> {
  _FakeStateProviderElement_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Ref].
///
/// See the documentation for Mockito's code generation for more information.
class MockRef<State extends Object?> extends _i1.Mock
    implements _i2.Ref<State> {
  @override
  _i2.ProviderContainer get container => (super.noSuchMethod(
        Invocation.getter(#container),
        returnValue: _FakeProviderContainer_0(
          this,
          Invocation.getter(#container),
        ),
        returnValueForMissingStub: _FakeProviderContainer_0(
          this,
          Invocation.getter(#container),
        ),
      ) as _i2.ProviderContainer);

  @override
  T refresh<T>(_i2.Refreshable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [provider],
        ),
        returnValue: _i7.dummyValue<T>(
          this,
          Invocation.method(
            #refresh,
            [provider],
          ),
        ),
        returnValueForMissingStub: _i7.dummyValue<T>(
          this,
          Invocation.method(
            #refresh,
            [provider],
          ),
        ),
      ) as T);

  @override
  void invalidate(_i2.ProviderOrFamily? provider) => super.noSuchMethod(
        Invocation.method(
          #invalidate,
          [provider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      State?,
      State,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateSelf() => super.noSuchMethod(
        Invocation.method(
          #invalidateSelf,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onAddListener(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onAddListener,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onRemoveListener(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onRemoveListener,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onResume(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onResume,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onCancel(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onCancel,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDispose(void Function()? cb) => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [cb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  T read<T>(_i2.ProviderListenable<T>? provider) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [provider],
        ),
        returnValue: _i7.dummyValue<T>(
          this,
          Invocation.method(
            #read,
            [provider],
          ),
        ),
        returnValueForMissingStub: _i7.dummyValue<T>(
          this,
          Invocation.method(
            #read,
            [provider],
          ),
        ),
      ) as T);

  @override
  bool exists(_i2.ProviderBase<Object?>? provider) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [provider],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  T watch<T>(_i2.AlwaysAliveProviderListenable<T>? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #watch,
          [provider],
        ),
        returnValue: _i7.dummyValue<T>(
          this,
          Invocation.method(
            #watch,
            [provider],
          ),
        ),
        returnValueForMissingStub: _i7.dummyValue<T>(
          this,
          Invocation.method(
            #watch,
            [provider],
          ),
        ),
      ) as T);

  @override
  _i2.ProviderSubscription<T> listen<T>(
    _i2.AlwaysAliveProviderListenable<T>? provider,
    void Function(
      T?,
      T,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
    bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listen,
          [
            provider,
            listener,
          ],
          {
            #onError: onError,
            #fireImmediately: fireImmediately,
          },
        ),
        returnValue: _FakeProviderSubscription_1<T>(
          this,
          Invocation.method(
            #listen,
            [
              provider,
              listener,
            ],
            {
              #onError: onError,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
        returnValueForMissingStub: _FakeProviderSubscription_1<T>(
          this,
          Invocation.method(
            #listen,
            [
              provider,
              listener,
            ],
            {
              #onError: onError,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
      ) as _i2.ProviderSubscription<T>);
}

/// A class which mocks [BonusInfoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBonusInfoRepository extends _i1.Mock
    implements _i8.BonusInfoRepository {
  @override
  _i9.Future<_i3.Box<_i10.BonusInfo>> openBox() => (super.noSuchMethod(
        Invocation.method(
          #openBox,
          [],
        ),
        returnValue: _i9.Future<_i3.Box<_i10.BonusInfo>>.value(
            _FakeBox_2<_i10.BonusInfo>(
          this,
          Invocation.method(
            #openBox,
            [],
          ),
        )),
        returnValueForMissingStub: _i9.Future<_i3.Box<_i10.BonusInfo>>.value(
            _FakeBox_2<_i10.BonusInfo>(
          this,
          Invocation.method(
            #openBox,
            [],
          ),
        )),
      ) as _i9.Future<_i3.Box<_i10.BonusInfo>>);

  @override
  _i9.Future<void> closeBox() => (super.noSuchMethod(
        Invocation.method(
          #closeBox,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> reopenBox() => (super.noSuchMethod(
        Invocation.method(
          #reopenBox,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<String> addBonusInfo(_i10.BonusInfo? bonusInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBonusInfo,
          [bonusInfo],
        ),
        returnValue: _i9.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #addBonusInfo,
            [bonusInfo],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #addBonusInfo,
            [bonusInfo],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<List<_i10.BonusInfo>> getAllBonusInfos() => (super.noSuchMethod(
        Invocation.method(
          #getAllBonusInfos,
          [],
        ),
        returnValue: _i9.Future<List<_i10.BonusInfo>>.value(<_i10.BonusInfo>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i10.BonusInfo>>.value(<_i10.BonusInfo>[]),
      ) as _i9.Future<List<_i10.BonusInfo>>);

  @override
  _i9.Future<void> updateBonusInfo(_i10.BonusInfo? bonusInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBonusInfo,
          [bonusInfo],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteBonusInfo(_i10.BonusInfo? info) => (super.noSuchMethod(
        Invocation.method(
          #deleteBonusInfo,
          [info],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<Map<String, double>> getAllRatiosToday() => (super.noSuchMethod(
        Invocation.method(
          #getAllRatiosToday,
          [],
        ),
        returnValue: _i9.Future<Map<String, double>>.value(<String, double>{}),
        returnValueForMissingStub:
            _i9.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i9.Future<Map<String, double>>);
}

/// A class which mocks [BonusInfoAndRatio].
///
/// See the documentation for Mockito's code generation for more information.
class MockBonusInfoAndRatio extends _i1.Mock implements _i5.BonusInfoAndRatio {
  @override
  List<_i10.BonusInfo> get bonusInfo => (super.noSuchMethod(
        Invocation.getter(#bonusInfo),
        returnValue: <_i10.BonusInfo>[],
        returnValueForMissingStub: <_i10.BonusInfo>[],
      ) as List<_i10.BonusInfo>);

  @override
  set bonusInfo(List<_i10.BonusInfo>? _bonusInfo) => super.noSuchMethod(
        Invocation.setter(
          #bonusInfo,
          _bonusInfo,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get ratio => (super.noSuchMethod(
        Invocation.getter(#ratio),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  set ratio(double? _ratio) => super.noSuchMethod(
        Invocation.setter(
          #ratio,
          _ratio,
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i6.UserRepository {
  @override
  _i9.Future<Map<String, dynamic>?> getUserData(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [userId],
        ),
        returnValue: _i9.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i9.Future<Map<String, dynamic>?>.value(),
      ) as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<bool> editWorkingHours(
    String? userId,
    double? newWorkingHours,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editWorkingHours,
          [
            userId,
            newWorkingHours,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> editPaidBreaks(
    String? userId,
    bool? newPaidBreaks,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editPaidBreaks,
          [
            userId,
            newPaidBreaks,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> editHourlyRate(
    String? userId,
    double? newHourlyRate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editHourlyRate,
          [
            userId,
            newHourlyRate,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
}

/// A class which mocks [StateNotifierProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockBonusInfoStateNotifierProvider extends _i1.Mock
    implements
        _i2
        .StateNotifierProvider<_i11.BonusInfoNotifier, _i5.BonusInfoAndRatio> {
  @override
  _i2.AlwaysAliveRefreshable<_i11.BonusInfoNotifier> get notifier =>
      (super.noSuchMethod(
        Invocation.getter(#notifier),
        returnValue: _FakeAlwaysAliveRefreshable_3<_i11.BonusInfoNotifier>(
          this,
          Invocation.getter(#notifier),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveRefreshable_3<_i11.BonusInfoNotifier>(
          this,
          Invocation.getter(#notifier),
        ),
      ) as _i2.AlwaysAliveRefreshable<_i11.BonusInfoNotifier>);

  @override
  _i2.StateNotifierProviderElement<
          _i11.BonusInfoNotifier, _i5.BonusInfoAndRatio>
      createElement() => (super.noSuchMethod(
            Invocation.method(
              #createElement,
              [],
            ),
            returnValue: _FakeStateNotifierProviderElement_4<
                _i11.BonusInfoNotifier, _i5.BonusInfoAndRatio>(
              this,
              Invocation.method(
                #createElement,
                [],
              ),
            ),
            returnValueForMissingStub: _FakeStateNotifierProviderElement_4<
                _i11.BonusInfoNotifier, _i5.BonusInfoAndRatio>(
              this,
              Invocation.method(
                #createElement,
                [],
              ),
            ),
          ) as _i2.StateNotifierProviderElement<_i11.BonusInfoNotifier,
              _i5.BonusInfoAndRatio>);

  @override
  _i2.Override overrideWith(
          _i2.Create<
                  _i11.BonusInfoNotifier,
                  _i2.StateNotifierProviderRef<_i11.BonusInfoNotifier,
                      _i5.BonusInfoAndRatio>>?
              create) =>
      (super.noSuchMethod(
        Invocation.method(
          #overrideWith,
          [create],
        ),
        returnValue: _FakeOverride_5(
          this,
          Invocation.method(
            #overrideWith,
            [create],
          ),
        ),
        returnValueForMissingStub: _FakeOverride_5(
          this,
          Invocation.method(
            #overrideWith,
            [create],
          ),
        ),
      ) as _i2.Override);

  @override
  _i2.ProviderSubscription<_i5.BonusInfoAndRatio> addListener(
    _i2.Node? node,
    void Function(
      _i5.BonusInfoAndRatio?,
      _i5.BonusInfoAndRatio,
    )? listener, {
    required void Function(
      Object,
      StackTrace,
    )? onError,
    required void Function()? onDependencyMayHaveChanged,
    required bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [
            node,
            listener,
          ],
          {
            #onError: onError,
            #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
            #fireImmediately: fireImmediately,
          },
        ),
        returnValue: _FakeProviderSubscription_1<_i5.BonusInfoAndRatio>(
          this,
          Invocation.method(
            #addListener,
            [
              node,
              listener,
            ],
            {
              #onError: onError,
              #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
        returnValueForMissingStub:
            _FakeProviderSubscription_1<_i5.BonusInfoAndRatio>(
          this,
          Invocation.method(
            #addListener,
            [
              node,
              listener,
            ],
            {
              #onError: onError,
              #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
      ) as _i2.ProviderSubscription<_i5.BonusInfoAndRatio>);

  @override
  _i5.BonusInfoAndRatio read(_i2.Node? node) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [node],
        ),
        returnValue: _FakeBonusInfoAndRatio_6(
          this,
          Invocation.method(
            #read,
            [node],
          ),
        ),
        returnValueForMissingStub: _FakeBonusInfoAndRatio_6(
          this,
          Invocation.method(
            #read,
            [node],
          ),
        ),
      ) as _i5.BonusInfoAndRatio);

  @override
  _i2.AlwaysAliveProviderListenable<Selected> select<Selected>(
          Selected Function(_i5.BonusInfoAndRatio)? selector) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [selector],
        ),
        returnValue: _FakeAlwaysAliveProviderListenable_7<Selected>(
          this,
          Invocation.method(
            #select,
            [selector],
          ),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveProviderListenable_7<Selected>(
          this,
          Invocation.method(
            #select,
            [selector],
          ),
        ),
      ) as _i2.AlwaysAliveProviderListenable<Selected>);
}

/// A class which mocks [StateNotifierProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserNotifierStateNotifierProvider extends _i1.Mock
    implements _i2.StateNotifierProvider<_i6.UserNotifier, _i6.UserState> {
  @override
  _i2.AlwaysAliveRefreshable<_i6.UserNotifier> get notifier =>
      (super.noSuchMethod(
        Invocation.getter(#notifier),
        returnValue: _FakeAlwaysAliveRefreshable_3<_i6.UserNotifier>(
          this,
          Invocation.getter(#notifier),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveRefreshable_3<_i6.UserNotifier>(
          this,
          Invocation.getter(#notifier),
        ),
      ) as _i2.AlwaysAliveRefreshable<_i6.UserNotifier>);

  @override
  _i2.StateNotifierProviderElement<_i6.UserNotifier, _i6.UserState>
      createElement() => (super.noSuchMethod(
            Invocation.method(
              #createElement,
              [],
            ),
            returnValue: _FakeStateNotifierProviderElement_4<_i6.UserNotifier,
                _i6.UserState>(
              this,
              Invocation.method(
                #createElement,
                [],
              ),
            ),
            returnValueForMissingStub: _FakeStateNotifierProviderElement_4<
                _i6.UserNotifier, _i6.UserState>(
              this,
              Invocation.method(
                #createElement,
                [],
              ),
            ),
          ) as _i2
              .StateNotifierProviderElement<_i6.UserNotifier, _i6.UserState>);

  @override
  _i2.Override overrideWith(
          _i2.Create<
                  _i6.UserNotifier,
                  _i2
                  .StateNotifierProviderRef<_i6.UserNotifier, _i6.UserState>>?
              create) =>
      (super.noSuchMethod(
        Invocation.method(
          #overrideWith,
          [create],
        ),
        returnValue: _FakeOverride_5(
          this,
          Invocation.method(
            #overrideWith,
            [create],
          ),
        ),
        returnValueForMissingStub: _FakeOverride_5(
          this,
          Invocation.method(
            #overrideWith,
            [create],
          ),
        ),
      ) as _i2.Override);

  @override
  _i2.ProviderSubscription<_i6.UserState> addListener(
    _i2.Node? node,
    void Function(
      _i6.UserState?,
      _i6.UserState,
    )? listener, {
    required void Function(
      Object,
      StackTrace,
    )? onError,
    required void Function()? onDependencyMayHaveChanged,
    required bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [
            node,
            listener,
          ],
          {
            #onError: onError,
            #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
            #fireImmediately: fireImmediately,
          },
        ),
        returnValue: _FakeProviderSubscription_1<_i6.UserState>(
          this,
          Invocation.method(
            #addListener,
            [
              node,
              listener,
            ],
            {
              #onError: onError,
              #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
        returnValueForMissingStub: _FakeProviderSubscription_1<_i6.UserState>(
          this,
          Invocation.method(
            #addListener,
            [
              node,
              listener,
            ],
            {
              #onError: onError,
              #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
      ) as _i2.ProviderSubscription<_i6.UserState>);

  @override
  _i6.UserState read(_i2.Node? node) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [node],
        ),
        returnValue: _FakeUserState_8(
          this,
          Invocation.method(
            #read,
            [node],
          ),
        ),
        returnValueForMissingStub: _FakeUserState_8(
          this,
          Invocation.method(
            #read,
            [node],
          ),
        ),
      ) as _i6.UserState);

  @override
  _i2.AlwaysAliveProviderListenable<Selected> select<Selected>(
          Selected Function(_i6.UserState)? selector) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [selector],
        ),
        returnValue: _FakeAlwaysAliveProviderListenable_7<Selected>(
          this,
          Invocation.method(
            #select,
            [selector],
          ),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveProviderListenable_7<Selected>(
          this,
          Invocation.method(
            #select,
            [selector],
          ),
        ),
      ) as _i2.AlwaysAliveProviderListenable<Selected>);
}

/// A class which mocks [StateProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockOvertimeRatioProvider extends _i1.Mock
    implements _i2.StateProvider<double> {
  @override
  _i2.AlwaysAliveRefreshable<_i12.StateController<double>> get notifier =>
      (super.noSuchMethod(
        Invocation.getter(#notifier),
        returnValue:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double>>(
          this,
          Invocation.getter(#notifier),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double>>(
          this,
          Invocation.getter(#notifier),
        ),
      ) as _i2.AlwaysAliveRefreshable<_i12.StateController<double>>);

  @override
  _i2.AlwaysAliveRefreshable<_i12.StateController<double>> get state =>
      (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double>>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double>>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AlwaysAliveRefreshable<_i12.StateController<double>>);

  @override
  _i2.StateProviderElement<double> createElement() => (super.noSuchMethod(
        Invocation.method(
          #createElement,
          [],
        ),
        returnValue: _FakeStateProviderElement_9<double>(
          this,
          Invocation.method(
            #createElement,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeStateProviderElement_9<double>(
          this,
          Invocation.method(
            #createElement,
            [],
          ),
        ),
      ) as _i2.StateProviderElement<double>);

  @override
  _i2.Override overrideWith(
          _i2.Create<double, _i2.StateProviderRef<double>>? create) =>
      (super.noSuchMethod(
        Invocation.method(
          #overrideWith,
          [create],
        ),
        returnValue: _FakeOverride_5(
          this,
          Invocation.method(
            #overrideWith,
            [create],
          ),
        ),
        returnValueForMissingStub: _FakeOverride_5(
          this,
          Invocation.method(
            #overrideWith,
            [create],
          ),
        ),
      ) as _i2.Override);

  @override
  _i2.ProviderSubscription<double> addListener(
    _i2.Node? node,
    void Function(
      double?,
      double,
    )? listener, {
    required void Function(
      Object,
      StackTrace,
    )? onError,
    required void Function()? onDependencyMayHaveChanged,
    required bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [
            node,
            listener,
          ],
          {
            #onError: onError,
            #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
            #fireImmediately: fireImmediately,
          },
        ),
        returnValue: _FakeProviderSubscription_1<double>(
          this,
          Invocation.method(
            #addListener,
            [
              node,
              listener,
            ],
            {
              #onError: onError,
              #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
        returnValueForMissingStub: _FakeProviderSubscription_1<double>(
          this,
          Invocation.method(
            #addListener,
            [
              node,
              listener,
            ],
            {
              #onError: onError,
              #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
      ) as _i2.ProviderSubscription<double>);

  @override
  double read(_i2.Node? node) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [node],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i2.AlwaysAliveProviderListenable<Selected> select<Selected>(
          Selected Function(double)? selector) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [selector],
        ),
        returnValue: _FakeAlwaysAliveProviderListenable_7<Selected>(
          this,
          Invocation.method(
            #select,
            [selector],
          ),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveProviderListenable_7<Selected>(
          this,
          Invocation.method(
            #select,
            [selector],
          ),
        ),
      ) as _i2.AlwaysAliveProviderListenable<Selected>);
}

/// A class which mocks [StateProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockOvertimeWorkingHoursState extends _i1.Mock
    implements _i2.StateProvider<double?> {
  @override
  _i2.AlwaysAliveRefreshable<_i12.StateController<double?>> get notifier =>
      (super.noSuchMethod(
        Invocation.getter(#notifier),
        returnValue:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double?>>(
          this,
          Invocation.getter(#notifier),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double?>>(
          this,
          Invocation.getter(#notifier),
        ),
      ) as _i2.AlwaysAliveRefreshable<_i12.StateController<double?>>);

  @override
  _i2.AlwaysAliveRefreshable<_i12.StateController<double?>> get state =>
      (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double?>>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double?>>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AlwaysAliveRefreshable<_i12.StateController<double?>>);

  @override
  _i2.StateProviderElement<double?> createElement() => (super.noSuchMethod(
        Invocation.method(
          #createElement,
          [],
        ),
        returnValue: _FakeStateProviderElement_9<double?>(
          this,
          Invocation.method(
            #createElement,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeStateProviderElement_9<double?>(
          this,
          Invocation.method(
            #createElement,
            [],
          ),
        ),
      ) as _i2.StateProviderElement<double?>);

  @override
  _i2.Override overrideWith(
          _i2.Create<double?, _i2.StateProviderRef<double?>>? create) =>
      (super.noSuchMethod(
        Invocation.method(
          #overrideWith,
          [create],
        ),
        returnValue: _FakeOverride_5(
          this,
          Invocation.method(
            #overrideWith,
            [create],
          ),
        ),
        returnValueForMissingStub: _FakeOverride_5(
          this,
          Invocation.method(
            #overrideWith,
            [create],
          ),
        ),
      ) as _i2.Override);

  @override
  _i2.ProviderSubscription<double?> addListener(
    _i2.Node? node,
    void Function(
      double?,
      double?,
    )? listener, {
    required void Function(
      Object,
      StackTrace,
    )? onError,
    required void Function()? onDependencyMayHaveChanged,
    required bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [
            node,
            listener,
          ],
          {
            #onError: onError,
            #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
            #fireImmediately: fireImmediately,
          },
        ),
        returnValue: _FakeProviderSubscription_1<double?>(
          this,
          Invocation.method(
            #addListener,
            [
              node,
              listener,
            ],
            {
              #onError: onError,
              #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
        returnValueForMissingStub: _FakeProviderSubscription_1<double?>(
          this,
          Invocation.method(
            #addListener,
            [
              node,
              listener,
            ],
            {
              #onError: onError,
              #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
      ) as _i2.ProviderSubscription<double?>);

  @override
  double? read(_i2.Node? node) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [node],
        ),
        returnValueForMissingStub: null,
      ) as double?);

  @override
  _i2.AlwaysAliveProviderListenable<Selected> select<Selected>(
          Selected Function(double?)? selector) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [selector],
        ),
        returnValue: _FakeAlwaysAliveProviderListenable_7<Selected>(
          this,
          Invocation.method(
            #select,
            [selector],
          ),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveProviderListenable_7<Selected>(
          this,
          Invocation.method(
            #select,
            [selector],
          ),
        ),
      ) as _i2.AlwaysAliveProviderListenable<Selected>);
}

/// A class which mocks [StateProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAllowanceProvider extends _i1.Mock
    implements _i2.StateProvider<double> {
  @override
  _i2.AlwaysAliveRefreshable<_i12.StateController<double>> get notifier =>
      (super.noSuchMethod(
        Invocation.getter(#notifier),
        returnValue:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double>>(
          this,
          Invocation.getter(#notifier),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double>>(
          this,
          Invocation.getter(#notifier),
        ),
      ) as _i2.AlwaysAliveRefreshable<_i12.StateController<double>>);

  @override
  _i2.AlwaysAliveRefreshable<_i12.StateController<double>> get state =>
      (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double>>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double>>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AlwaysAliveRefreshable<_i12.StateController<double>>);

  @override
  _i2.StateProviderElement<double> createElement() => (super.noSuchMethod(
        Invocation.method(
          #createElement,
          [],
        ),
        returnValue: _FakeStateProviderElement_9<double>(
          this,
          Invocation.method(
            #createElement,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeStateProviderElement_9<double>(
          this,
          Invocation.method(
            #createElement,
            [],
          ),
        ),
      ) as _i2.StateProviderElement<double>);

  @override
  _i2.Override overrideWith(
          _i2.Create<double, _i2.StateProviderRef<double>>? create) =>
      (super.noSuchMethod(
        Invocation.method(
          #overrideWith,
          [create],
        ),
        returnValue: _FakeOverride_5(
          this,
          Invocation.method(
            #overrideWith,
            [create],
          ),
        ),
        returnValueForMissingStub: _FakeOverride_5(
          this,
          Invocation.method(
            #overrideWith,
            [create],
          ),
        ),
      ) as _i2.Override);

  @override
  _i2.ProviderSubscription<double> addListener(
    _i2.Node? node,
    void Function(
      double?,
      double,
    )? listener, {
    required void Function(
      Object,
      StackTrace,
    )? onError,
    required void Function()? onDependencyMayHaveChanged,
    required bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [
            node,
            listener,
          ],
          {
            #onError: onError,
            #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
            #fireImmediately: fireImmediately,
          },
        ),
        returnValue: _FakeProviderSubscription_1<double>(
          this,
          Invocation.method(
            #addListener,
            [
              node,
              listener,
            ],
            {
              #onError: onError,
              #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
        returnValueForMissingStub: _FakeProviderSubscription_1<double>(
          this,
          Invocation.method(
            #addListener,
            [
              node,
              listener,
            ],
            {
              #onError: onError,
              #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
      ) as _i2.ProviderSubscription<double>);

  @override
  double read(_i2.Node? node) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [node],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i2.AlwaysAliveProviderListenable<Selected> select<Selected>(
          Selected Function(double)? selector) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [selector],
        ),
        returnValue: _FakeAlwaysAliveProviderListenable_7<Selected>(
          this,
          Invocation.method(
            #select,
            [selector],
          ),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveProviderListenable_7<Selected>(
          this,
          Invocation.method(
            #select,
            [selector],
          ),
        ),
      ) as _i2.AlwaysAliveProviderListenable<Selected>);
}

/// A class which mocks [StateProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTargetProvider extends _i1.Mock implements _i2.StateProvider<double> {
  @override
  _i2.AlwaysAliveRefreshable<_i12.StateController<double>> get notifier =>
      (super.noSuchMethod(
        Invocation.getter(#notifier),
        returnValue:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double>>(
          this,
          Invocation.getter(#notifier),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double>>(
          this,
          Invocation.getter(#notifier),
        ),
      ) as _i2.AlwaysAliveRefreshable<_i12.StateController<double>>);

  @override
  _i2.AlwaysAliveRefreshable<_i12.StateController<double>> get state =>
      (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double>>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveRefreshable_3<_i12.StateController<double>>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AlwaysAliveRefreshable<_i12.StateController<double>>);

  @override
  _i2.StateProviderElement<double> createElement() => (super.noSuchMethod(
        Invocation.method(
          #createElement,
          [],
        ),
        returnValue: _FakeStateProviderElement_9<double>(
          this,
          Invocation.method(
            #createElement,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeStateProviderElement_9<double>(
          this,
          Invocation.method(
            #createElement,
            [],
          ),
        ),
      ) as _i2.StateProviderElement<double>);

  @override
  _i2.Override overrideWith(
          _i2.Create<double, _i2.StateProviderRef<double>>? create) =>
      (super.noSuchMethod(
        Invocation.method(
          #overrideWith,
          [create],
        ),
        returnValue: _FakeOverride_5(
          this,
          Invocation.method(
            #overrideWith,
            [create],
          ),
        ),
        returnValueForMissingStub: _FakeOverride_5(
          this,
          Invocation.method(
            #overrideWith,
            [create],
          ),
        ),
      ) as _i2.Override);

  @override
  _i2.ProviderSubscription<double> addListener(
    _i2.Node? node,
    void Function(
      double?,
      double,
    )? listener, {
    required void Function(
      Object,
      StackTrace,
    )? onError,
    required void Function()? onDependencyMayHaveChanged,
    required bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [
            node,
            listener,
          ],
          {
            #onError: onError,
            #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
            #fireImmediately: fireImmediately,
          },
        ),
        returnValue: _FakeProviderSubscription_1<double>(
          this,
          Invocation.method(
            #addListener,
            [
              node,
              listener,
            ],
            {
              #onError: onError,
              #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
        returnValueForMissingStub: _FakeProviderSubscription_1<double>(
          this,
          Invocation.method(
            #addListener,
            [
              node,
              listener,
            ],
            {
              #onError: onError,
              #onDependencyMayHaveChanged: onDependencyMayHaveChanged,
              #fireImmediately: fireImmediately,
            },
          ),
        ),
      ) as _i2.ProviderSubscription<double>);

  @override
  double read(_i2.Node? node) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [node],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i2.AlwaysAliveProviderListenable<Selected> select<Selected>(
          Selected Function(double)? selector) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [selector],
        ),
        returnValue: _FakeAlwaysAliveProviderListenable_7<Selected>(
          this,
          Invocation.method(
            #select,
            [selector],
          ),
        ),
        returnValueForMissingStub:
            _FakeAlwaysAliveProviderListenable_7<Selected>(
          this,
          Invocation.method(
            #select,
            [selector],
          ),
        ),
      ) as _i2.AlwaysAliveProviderListenable<Selected>);
}
