// Mocks generated by Mockito 5.4.5 from annotations
// in ballistics_wallet_flutter/test/wallet/bonus_info_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:io' as _i17;

import 'package:ballistics_wallet_flutter/models/bonus_info.dart' as _i11;
import 'package:ballistics_wallet_flutter/models/monthly_historical_data.dart'
    as _i21;
import 'package:ballistics_wallet_flutter/models/product_info.dart' as _i14;
import 'package:ballistics_wallet_flutter/models/ratio_and_bonus_info.dart'
    as _i8;
import 'package:ballistics_wallet_flutter/models/settings.dart' as _i18;
import 'package:ballistics_wallet_flutter/providers/product_info_provider.dart'
    as _i19;
import 'package:ballistics_wallet_flutter/providers/wallet_providers.dart'
    as _i20;
import 'package:ballistics_wallet_flutter/repository/auth_repository.dart'
    as _i5;
import 'package:ballistics_wallet_flutter/repository/back_up_repository.dart'
    as _i7;
import 'package:ballistics_wallet_flutter/repository/bonus_info_repository.dart'
    as _i9;
import 'package:ballistics_wallet_flutter/repository/product_info_repository.dart'
    as _i13;
import 'package:ballistics_wallet_flutter/repository/users_repository.dart'
    as _i4;
import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i15;
import 'package:hive/hive.dart' as _i2;
import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:state_notifier/state_notifier.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_1 extends _i1.SmartFake
    implements _i3.FirebaseFirestore {
  _FakeFirebaseFirestore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRepository_2 extends _i1.SmartFake
    implements _i4.UserRepository {
  _FakeUserRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserState_3 extends _i1.SmartFake implements _i4.UserState {
  _FakeUserState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthRepository_4 extends _i1.SmartFake
    implements _i5.AuthRepository {
  _FakeAuthRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_5 extends _i1.SmartFake implements _i6.Client {
  _FakeClient_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBackupState_6 extends _i1.SmartFake implements _i7.BackupState {
  _FakeBackupState_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBonusInfoAndRatio_7 extends _i1.SmartFake
    implements _i8.BonusInfoAndRatio {
  _FakeBonusInfoAndRatio_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BonusInfoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBonusInfoRepository extends _i1.Mock
    implements _i9.BonusInfoRepository {
  @override
  _i10.Future<_i2.Box<_i11.BonusInfo>> openBox() => (super.noSuchMethod(
        Invocation.method(
          #openBox,
          [],
        ),
        returnValue: _i10.Future<_i2.Box<_i11.BonusInfo>>.value(
            _FakeBox_0<_i11.BonusInfo>(
          this,
          Invocation.method(
            #openBox,
            [],
          ),
        )),
        returnValueForMissingStub: _i10.Future<_i2.Box<_i11.BonusInfo>>.value(
            _FakeBox_0<_i11.BonusInfo>(
          this,
          Invocation.method(
            #openBox,
            [],
          ),
        )),
      ) as _i10.Future<_i2.Box<_i11.BonusInfo>>);

  @override
  _i10.Future<void> closeBox() => (super.noSuchMethod(
        Invocation.method(
          #closeBox,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> reopenBox() => (super.noSuchMethod(
        Invocation.method(
          #reopenBox,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String> addBonusInfo(_i11.BonusInfo? bonusInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBonusInfo,
          [bonusInfo],
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #addBonusInfo,
            [bonusInfo],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #addBonusInfo,
            [bonusInfo],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<List<_i11.BonusInfo>> getAllBonusInfos() => (super.noSuchMethod(
        Invocation.method(
          #getAllBonusInfos,
          [],
        ),
        returnValue:
            _i10.Future<List<_i11.BonusInfo>>.value(<_i11.BonusInfo>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i11.BonusInfo>>.value(<_i11.BonusInfo>[]),
      ) as _i10.Future<List<_i11.BonusInfo>>);

  @override
  _i10.Future<void> updateBonusInfo(_i11.BonusInfo? bonusInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBonusInfo,
          [bonusInfo],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteBonusInfo(_i11.BonusInfo? info) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBonusInfo,
          [info],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<Map<String, double>> getAllRatiosToday() => (super.noSuchMethod(
        Invocation.method(
          #getAllRatiosToday,
          [],
        ),
        returnValue: _i10.Future<Map<String, double>>.value(<String, double>{}),
        returnValueForMissingStub:
            _i10.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i10.Future<Map<String, double>>);
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox extends _i1.Mock implements _i2.Box<_i11.BonusInfo> {
  @override
  Iterable<_i11.BonusInfo> get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: <_i11.BonusInfo>[],
        returnValueForMissingStub: <_i11.BonusInfo>[],
      ) as Iterable<_i11.BonusInfo>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get lazy => (super.noSuchMethod(
        Invocation.getter(#lazy),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Iterable<dynamic> get keys => (super.noSuchMethod(
        Invocation.getter(#keys),
        returnValue: <dynamic>[],
        returnValueForMissingStub: <dynamic>[],
      ) as Iterable<dynamic>);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Iterable<_i11.BonusInfo> valuesBetween({
    dynamic startKey,
    dynamic endKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #valuesBetween,
          [],
          {
            #startKey: startKey,
            #endKey: endKey,
          },
        ),
        returnValue: <_i11.BonusInfo>[],
        returnValueForMissingStub: <_i11.BonusInfo>[],
      ) as Iterable<_i11.BonusInfo>);

  @override
  _i11.BonusInfo? getAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #getAt,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i11.BonusInfo?);

  @override
  Map<dynamic, _i11.BonusInfo> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <dynamic, _i11.BonusInfo>{},
        returnValueForMissingStub: <dynamic, _i11.BonusInfo>{},
      ) as Map<dynamic, _i11.BonusInfo>);

  @override
  dynamic keyAt(int? index) => super.noSuchMethod(
        Invocation.method(
          #keyAt,
          [index],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Stream<_i2.BoxEvent> watch({dynamic key}) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#key: key},
        ),
        returnValue: _i10.Stream<_i2.BoxEvent>.empty(),
        returnValueForMissingStub: _i10.Stream<_i2.BoxEvent>.empty(),
      ) as _i10.Stream<_i2.BoxEvent>);

  @override
  bool containsKey(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Future<void> put(
    dynamic key,
    _i11.BonusInfo? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> putAt(
    int? index,
    _i11.BonusInfo? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAt,
          [
            index,
            value,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> putAll(Map<dynamic, _i11.BonusInfo>? entries) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> add(_i11.BonusInfo? value) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValue: _i10.Future<int>.value(0),
        returnValueForMissingStub: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<Iterable<int>> addAll(Iterable<_i11.BonusInfo>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAll,
          [values],
        ),
        returnValue: _i10.Future<Iterable<int>>.value(<int>[]),
        returnValueForMissingStub: _i10.Future<Iterable<int>>.value(<int>[]),
      ) as _i10.Future<Iterable<int>>);

  @override
  _i10.Future<void> delete(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteAt,
          [index],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteAll(Iterable<dynamic>? keys) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [keys],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> compact() => (super.noSuchMethod(
        Invocation.method(
          #compact,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i10.Future<int>.value(0),
        returnValueForMissingStub: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [ProductInfoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductInfoRepository extends _i1.Mock
    implements _i13.ProductInfoRepository {
  @override
  _i3.FirebaseFirestore get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeFirebaseFirestore_1(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_1(
          this,
          Invocation.getter(#db),
        ),
      ) as _i3.FirebaseFirestore);

  @override
  _i10.Future<List<_i14.ProductInfo>> fetchProductInfo() => (super.noSuchMethod(
        Invocation.method(
          #fetchProductInfo,
          [],
        ),
        returnValue:
            _i10.Future<List<_i14.ProductInfo>>.value(<_i14.ProductInfo>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i14.ProductInfo>>.value(<_i14.ProductInfo>[]),
      ) as _i10.Future<List<_i14.ProductInfo>>);

  @override
  _i10.Future<void> addProduct(
    String? productName,
    int? target,
    List<_i14.Pressing>? pressings,
    bool? ayr,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProduct,
          [
            productName,
            target,
            pressings,
            ayr,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> editProductInfo(_i14.ProductInfo? updatedProduct) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProductInfo,
          [updatedProduct],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> deleteProduct(String? productName) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [productName],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [UserNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserNotifier extends _i1.Mock implements _i4.UserNotifier {
  @override
  _i4.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_2(
          this,
          Invocation.getter(#userRepository),
        ),
        returnValueForMissingStub: _FakeUserRepository_2(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i4.UserRepository);

  @override
  set onError(_i15.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Stream<_i4.UserState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i10.Stream<_i4.UserState>.empty(),
        returnValueForMissingStub: _i10.Stream<_i4.UserState>.empty(),
      ) as _i10.Stream<_i4.UserState>);

  @override
  _i4.UserState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeUserState_3(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeUserState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.UserState);

  @override
  set state(_i4.UserState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.UserState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeUserState_3(
          this,
          Invocation.getter(#debugState),
        ),
        returnValueForMissingStub: _FakeUserState_3(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i4.UserState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double calculateEffectiveWorkingHours(double? workingHours) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateEffectiveWorkingHours,
          [workingHours],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i10.Future<void> dontAskAgain(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #dontAskAgain,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> doBackUp(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #doBackUp,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> loadUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #loadUser,
          [userId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> updateUserSettings(
    double? newWorkingHours,
    double? newHourlyRate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserSettings,
          [
            newWorkingHours,
            newHourlyRate,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> editPaidBreaks(bool? newPaidBreaks) => (super.noSuchMethod(
        Invocation.method(
          #editPaidBreaks,
          [newPaidBreaks],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> updateUser(_i4.UserState? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  bool updateShouldNotify(
    _i4.UserState? old,
    _i4.UserState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i15.RemoveListener addListener(
    _i16.Listener<_i4.UserState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i15.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BackupManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupManager extends _i1.Mock implements _i7.BackupManager {
  @override
  _i5.AuthRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthRepository_4(
          this,
          Invocation.getter(#authRepository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_4(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i5.AuthRepository);

  @override
  set authRepository(_i5.AuthRepository? _authRepository) => super.noSuchMethod(
        Invocation.setter(
          #authRepository,
          _authRepository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Client get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeClient_5(
          this,
          Invocation.getter(#httpClient),
        ),
        returnValueForMissingStub: _FakeClient_5(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i6.Client);

  @override
  set onError(_i15.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Stream<_i7.BackupState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i10.Stream<_i7.BackupState>.empty(),
        returnValueForMissingStub: _i10.Stream<_i7.BackupState>.empty(),
      ) as _i10.Stream<_i7.BackupState>);

  @override
  _i7.BackupState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBackupState_6(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeBackupState_6(
          this,
          Invocation.getter(#state),
        ),
      ) as _i7.BackupState);

  @override
  set state(_i7.BackupState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.BackupState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeBackupState_6(
          this,
          Invocation.getter(#debugState),
        ),
        returnValueForMissingStub: _FakeBackupState_6(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i7.BackupState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Future<bool> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> backupData() => (super.noSuchMethod(
        Invocation.method(
          #backupData,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> zipHiveFiles(
    String? sourceDirPath,
    String? zipFilePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #zipHiveFiles,
          [
            sourceDirPath,
            zipFilePath,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> uploadFileToDrive(_i17.File? file) => (super.noSuchMethod(
        Invocation.method(
          #uploadFileToDrive,
          [file],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> prompt(String? url) => (super.noSuchMethod(
        Invocation.method(
          #prompt,
          [url],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i17.File?> downloadBackupFile() => (super.noSuchMethod(
        Invocation.method(
          #downloadBackupFile,
          [],
        ),
        returnValue: _i10.Future<_i17.File?>.value(),
        returnValueForMissingStub: _i10.Future<_i17.File?>.value(),
      ) as _i10.Future<_i17.File?>);

  @override
  _i10.Future<void> extractAndOverwriteHiveData(_i17.File? zipFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractAndOverwriteHiveData,
          [zipFile],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> restoreBackup() => (super.noSuchMethod(
        Invocation.method(
          #restoreBackup,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> checkActiveState() => (super.noSuchMethod(
        Invocation.method(
          #checkActiveState,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  bool updateShouldNotify(
    _i7.BackupState? old,
    _i7.BackupState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i15.RemoveListener addListener(
    _i16.Listener<_i7.BackupState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i15.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i4.UserRepository {
  @override
  _i10.Future<_i18.UserSettings?> getUserData(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [userId],
        ),
        returnValue: _i10.Future<_i18.UserSettings?>.value(),
        returnValueForMissingStub: _i10.Future<_i18.UserSettings?>.value(),
      ) as _i10.Future<_i18.UserSettings?>);

  @override
  _i10.Future<void> saveOrUpdateUserData(_i18.UserSettings? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOrUpdateUserData,
          [user],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> editWorkingHours(
    String? userId,
    double? newWorkingHours,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editWorkingHours,
          [
            userId,
            newWorkingHours,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> editPaidBreaks(
    String? userId,
    bool? newPaidBreaks,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editPaidBreaks,
          [
            userId,
            newPaidBreaks,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> editHourlyRate(
    String? userId,
    double? newHourlyRate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editHourlyRate,
          [
            userId,
            newHourlyRate,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  double calculateEffectiveWorkingHours(double? workingHours) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateEffectiveWorkingHours,
          [workingHours],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);
}

/// A class which mocks [ProductInfoNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductInfoNotifier extends _i1.Mock
    implements _i19.ProductInfoNotifier {
  @override
  set onError(_i15.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Stream<List<_i14.ProductInfo>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i10.Stream<List<_i14.ProductInfo>>.empty(),
        returnValueForMissingStub: _i10.Stream<List<_i14.ProductInfo>>.empty(),
      ) as _i10.Stream<List<_i14.ProductInfo>>);

  @override
  List<_i14.ProductInfo> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: <_i14.ProductInfo>[],
        returnValueForMissingStub: <_i14.ProductInfo>[],
      ) as List<_i14.ProductInfo>);

  @override
  set state(List<_i14.ProductInfo>? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i14.ProductInfo> get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: <_i14.ProductInfo>[],
        returnValueForMissingStub: <_i14.ProductInfo>[],
      ) as List<_i14.ProductInfo>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Future<void> loadProductInfo() => (super.noSuchMethod(
        Invocation.method(
          #loadProductInfo,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> addProductInfo(
    String? productName,
    int? target,
    List<_i14.Pressing>? pressings,
    bool? ayr,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProductInfo,
          [
            productName,
            target,
            pressings,
            ayr,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> editProductInfo(_i14.ProductInfo? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProductInfo,
          [product],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> deleteProduct(String? productName) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [productName],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  bool updateShouldNotify(
    List<_i14.ProductInfo>? old,
    List<_i14.ProductInfo>? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i15.RemoveListener addListener(
    _i16.Listener<List<_i14.ProductInfo>>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i15.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BonusInfoNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockBonusInfoNotifier extends _i1.Mock implements _i20.BonusInfoNotifier {
  @override
  String get userId => (super.noSuchMethod(
        Invocation.getter(#userId),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#userId),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#userId),
        ),
      ) as String);

  @override
  set onError(_i15.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Stream<_i8.BonusInfoAndRatio> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i10.Stream<_i8.BonusInfoAndRatio>.empty(),
        returnValueForMissingStub: _i10.Stream<_i8.BonusInfoAndRatio>.empty(),
      ) as _i10.Stream<_i8.BonusInfoAndRatio>);

  @override
  _i8.BonusInfoAndRatio get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBonusInfoAndRatio_7(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeBonusInfoAndRatio_7(
          this,
          Invocation.getter(#state),
        ),
      ) as _i8.BonusInfoAndRatio);

  @override
  set state(_i8.BonusInfoAndRatio? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.BonusInfoAndRatio get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeBonusInfoAndRatio_7(
          this,
          Invocation.getter(#debugState),
        ),
        returnValueForMissingStub: _FakeBonusInfoAndRatio_7(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i8.BonusInfoAndRatio);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> refreshHive() => (super.noSuchMethod(
        Invocation.method(
          #refreshHive,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void updateRatio(
    String? productName,
    int? productTarget,
    int? userNumber,
    double? workingHours,
    double? allowanceProvided,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateRatio,
          [
            productName,
            productTarget,
            userNumber,
            workingHours,
            allowanceProvided,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  double getProductRatio(String? productName) => (super.noSuchMethod(
        Invocation.method(
          #getProductRatio,
          [productName],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i10.Future<void> loadBonusInfos() => (super.noSuchMethod(
        Invocation.method(
          #loadBonusInfos,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String> addBonusInfo(_i11.BonusInfo? bonusInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBonusInfo,
          [bonusInfo],
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #addBonusInfo,
            [bonusInfo],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #addBonusInfo,
            [bonusInfo],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> updateBonusInfo(_i11.BonusInfo? bonusInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBonusInfo,
          [bonusInfo],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteBonusInfo(_i11.BonusInfo? info) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBonusInfo,
          [info],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<double> getTotalWorkingHours() => (super.noSuchMethod(
        Invocation.method(
          #getTotalWorkingHours,
          [],
        ),
        returnValue: _i10.Future<double>.value(0.0),
        returnValueForMissingStub: _i10.Future<double>.value(0.0),
      ) as _i10.Future<double>);

  @override
  _i10.Future<double> getTotalBonus() => (super.noSuchMethod(
        Invocation.method(
          #getTotalBonus,
          [],
        ),
        returnValue: _i10.Future<double>.value(0.0),
        returnValueForMissingStub: _i10.Future<double>.value(0.0),
      ) as _i10.Future<double>);

  @override
  _i10.Future<List<_i21.MonthlyData>> getHistoricalMonthlyData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistoricalMonthlyData,
          [],
        ),
        returnValue:
            _i10.Future<List<_i21.MonthlyData>>.value(<_i21.MonthlyData>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i21.MonthlyData>>.value(<_i21.MonthlyData>[]),
      ) as _i10.Future<List<_i21.MonthlyData>>);

  @override
  bool updateShouldNotify(
    _i8.BonusInfoAndRatio? old,
    _i8.BonusInfoAndRatio? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i15.RemoveListener addListener(
    _i16.Listener<_i8.BonusInfoAndRatio>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i15.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
