import 'package:hive/hive.dart';

part 'selected_product_history.g.dart';  // Name of the TypeAdapter generated by Hive

@HiveType(typeId: 2)
class SelectedProduct {

  SelectedProduct({required this.name, required this.selectedDate, required this.target});
  @HiveField(0)
  final String name;

  @HiveField(1)
  final DateTime selectedDate;

  @HiveField(2)
  final int target;
}
